api/api.py
Add an extra filter to the Vehicle API of ID. This has advantages of:
- The ability to look up the vehicle when the ID is the only thing known
- The ability to update data based on the previously saved ID so a lookup is not required again
=> Add ID filter to Vehicle API

buses/settings.py
Not sure what the 'true' or 'false' is meant to be so I just guessed based off the past few ones put in. 
I personally created the Glen Valley BODS file and uploaded it being PTI compliant so I know it is the correct information.
Also added Stagecoach in Chester to the Stagecoach list. For some reason, Stagecoach has started differentiating. I'll be honest, I kind of did it based off what I can see in the other entries.
=> Added Glen Valley BODS

buses/settings.py
Lakeside BODS is wrong because they have it all on different datasets and for some reason, at least 2 routes are missing. The Whitchurch Circular bus and Ellesmere to Shrewsbury.
Link Network BODS added because there are schools missing on the Traveline timetable.
=> Added Link Network BODS. Removed Lakeside BODS

data/operators.yaml
Amended Arrivas links because they were linking to an error 404 page. The local pages give less information now too so it made sense to link to the main homepage. 
Also added a good few missing links for operators. 
Made Stagecoach Chester into named Stagecoach Merseyside and South Lancashire (SCMY) with the hope that it merges them. The Stagecoach Chester 'operator' only has half of the Chester routes so it is misleading to have them showing up as they are. 
Renamed Hallmark Connections and Courtney Buses to their new names. For some reason, the operators haven't sorted out their NOC codes yet.
=> Edited some links & added a lot more operators

.dockerignore, .gitignore, Dockerfile, README.md, docker-compose.yml
I found it tricky to understand the whole process of bringing the environment up, so I figured it out and put it all in the `docker-compose`.
This should help others getting started on the project, and the existing workflow can remain if you define your own `.env` file (docker-compose will automatically pick that up).
=> Add full docker-compose startup

vehicles/forms.py
the fleet number field would be disabled but the text label would be placed beneath the reg number field. this fixes it by changing 'reg' to 'fleet_number'
example: https://bustimes.org/vehicles/20834/edit
the rest of the logic implemented remains untouched
=> fix ETM code change label position

buses/settings.py
These Merseyside Operators have their BODS timetables sorted by Merseytravel (the PTE) so should all be correct and work.
=> Added Merseyside Operators

buses/settings.py
Removing Hattons from normal BODS to see if the BODS or Ticketer datasets are best since two of the routes are messed up
https://bustimes.org/services/630-wigan-platt-bridge-via-ince
https://bustimes.org/services/613-top-lock-wigan
Duplicated times and the buses only run hourly so the times may be wrong.
=> Hattons is in twice

buses/settings.py
Tidied up the Ticketer Operators into easier to read groups. Either area code or operator parent group (whichever is more suitable) to make it easier to find any problem ops. 
Also moved GoNorthWest to the Passenger Operators as this will work with the new way of getting Passenger Operator data (using data.passenger rather than the direct websites)
Removed Reading Buses from BODS list as their data comes from Passenger.
=> Tidied Ticketer Ops & Moved GNW

buses/settings.py
Data is now showing 'from 6th June' so not useful for immediate travel. Data should come from Ticketer
=> Removed WOB Passenger Data

busstops/static/css/_base.scss
Sets nowrap for the route number text so that it doesn't fall onto a second line for 4+ digits
Before
After
=> minor change to stop departure css

fixtures/operators.yaml
Traveline NOC Database suggests is showing me that WNGS was updated on 1st June (and contact details are showing as the correct ones). and as such this could get removed. Just doing the # thing though until it refreshes to make sure.
=> Testing removing Diamond

buses/settings.py
This is so the vehicle tracking trips will match with the timetable correctly, as the current Traveline timetables have mismatching service numbers.
=> Move L & G Coaches over to Ticketer feed

fixtures/operators.yaml
Currently AMSY and ANNW show up as Arriva North West which is very confusing.
=> Arriva Merseyside Name

fixtures/operators.yaml
- Johns Taxis removed (operator no longer runs buses) 
- Updated Transpora North West email address.
- Changed LNNE (Old Link Network NOC Code) to MDBC (New noc code. The website that they have is not updated so daft to promote it) 
- Removed McGills West Twitter as they have updated their NOC entry. 
- Updated McGills Scotland East contact details.
- Updated Diamond South Easts NOC code since the current link directs to a 404 page.
- Minsterley Motors Twitter removed.
=> Updated operators info

api/serializers.py
Quite a few cases of service mode being blank, useful having operator mode as a fallback.
=> Re-add mode to API trip operator info

fixtures/operators.yaml
JKHY was a legacy entry for Hodgsons no longer used, HDGS can now go back to its default name of "Hodgsons"
edited NYCC name, url and twitter to reflect the new unitary authority change
=> removal of JKHY/HDGS and edit to NYCC to reflect new unitary authority

busstops/models.py
To stop https://bustimes.org/services/m92-hillsborough-harley-2 showing megabus awin link. 
the proper M92 falls under `MEGA` anyway so is still caught
=> remove M92 reference from is_megabus

fixtures/operators.yaml
Transdev are now using YCST NOC code on their open data. URL correct but name is just 'Coastliner'. Reverting to Transdev York as previous fixtures.
=> Update Operator Fixtures

fixtures/operators.yaml
Bright Bus is under Eastern Scottish as MESC. I know this is more of a bandaid, but given they are both PM0000923 I can't imagine why this wouldn't work. Eastern Scottish as a brand name is dead, so it ought not to be on here.
=> update operators.yaml (MESC as Bright Bus)

fixtures/operators.yaml
For some reason Edinburgh tenders have been put under MESC rather than MBLB.
=> Removes MESC as they now have normal service runs

vehicles/forms.py
Features and branding not needed on spare ticket machines. Removing as most other fields are removed so these two make sense.
=> Make spare machines slightly less editable

bustimes/management/commands/import_atco_cif.py
Y20 datasets are all dated from a long time ago and the data included in them either seems to be superseded.
=> Ignore Y20 folders on NI data

vehicles/templates/vehicle_revision.html
As per Discord suggestion: https://discord.com/channels/981008654536966224/1336575686160285737
For approve/disprove, if a user is not trusted, it should show 'approved by trusted user' 
If a user is trusted though, it should show 'approved by user [id]'
This should help to reduce abuse towards approvers but still enable trusted users to report anyone abusing trusted permissions and tackle any issues with edits.
=> Remove userid on approved/disproved for non trusted

vehicles/views.py
This should allow users to select pending and disapproved from the status field.
I am unable to test it, but as long as I have the correct way of getting the user IDs, the logic expression should hopefully work. Unless of course I am missing anything?
=> Allow users to see their own pending and disapproved edits

bustimes/management/commands/import_gtfs_flixbus.py
Currently Flixbus London-Europe services come into Bustimes via BODs but the data is awful and becomes bugged when Flixbus GTFS refreshes. Hopefully this way London-Europe routes show up more accurate data and so the europe data doesn't bug out each week
=> Hopefully picks up Flixbus London-Europe routes via Flixbus GTFS

vehicles/views.py
In my previous commit I forgot that Python is type sensitive when making comparisons - since one was a string and the other was an integer it would always return False and not work. This commit fixes that, and I have now managed to test this in a local instance
=> Fix to actually allow users to see their own disapproved edits

accounts/forms.py, accounts/tests.py
Unless someones username is just full stops, 150 characters doesnt fit onto almost any screen. 50 characters should be more than enough so that usernames aren't needlessly much wider than the screen but should also be enough that people are happy with their usernames.
Discord Bug report: https://discord.com/channels/981008654536966224/1299411686503088200
=> Reducing username length to 50 chars

fixtures/operators.yaml
The [@A2bbusandcoach](https://x.com/A2bbusandcoach) twitter account no longer exists. They use [@a2btravelgroup](https://x.com/a2btravelgroup) now.
This PR updates the `operators.yml` file to manually correct their Twitter.
=> Fix A2B's twitter

fixtures/operators.yaml
Not sure on the story but Ashwood are using this NOC code despite it being allocated to an old O licence holder in Scotland. Just doing this incase the admin panel doesn't save my temp override.
=> Ashwood Travel

bustimes/management/commands/import_gtfs_ember.py
Ember's GTFS static URL is changing, with the static file now served by a CDN rather than via API. The realtime URL remains unchanged.
=> Update Ember GTFS URL to latest static file
